import { createContext, useContext, useMemo, useState } from "react";

const translations = {
  EN: {
    home: "Home",
    about: "About",
    departments: "Departments",
    doctors: "Doctors",
    contact: "Contact",
    admin: "Admin",
    hindi: "Hindi",
    english: "English",
    patientLogin: "Patient Login",
    logout: "Logout",
    bookAppointment: "Book Appointment",
    viewDepartments: "View Departments",
    premiumHospital: "Premium modern hospital",
    heroTitle: "Healthcare that feels calm, precise, and beautifully organized.",
    heroText: "{hospital} combines expert doctors, digital appointment booking, 24/7 emergency care, and a premium patient experience.",
    doctorsStat: "Doctors",
    yearsStat: "Years",
    yearsShort: "yrs",
    satisfactionStat: "Satisfaction",
    liveEmergency: "Live emergency command",
    certifiedCare: "Certified specialty care",
    whyChoose: "Why choose us",
    professionalCare: "Professional care with premium digital access.",
    specialistLed: "Specialist-led treatment",
    specialistLedText: "Consult experienced doctors across high-demand clinical departments.",
    fastAppointments: "Fast appointments",
    fastAppointmentsText: "Patients can register, login, and book appointments through a secure flow.",
    premiumExperience: "Premium experience",
    premiumExperienceText: "Clean UI, smooth hover interactions, and responsive healthcare layouts.",
    aboutHospital: "About hospital",
    aboutTitle: "{hospital} is built for modern, trustworthy healthcare.",
    aboutText1: "We provide multispecialty care through senior consultants, modern diagnostics, integrated emergency response, and patient-first digital services.",
    aboutText2: "The platform includes patient authentication, appointment booking, admin dashboards, doctor management, inquiry tracking, and role-based access.",
    emergencyCare: "Emergency care",
    eightMin: "8 min",
    avgResponse: "Average response",
    qualityOps: "Quality-led operations",
    departmentsTitle: "Specialty care centers for every stage of treatment.",
    doctorsTitle: "Meet senior consultants across premium care departments.",
    appointmentBooking: "Appointment booking",
    loginFirstTitle: "Login first to book your hospital appointment.",
    loginFirstText: "Patient login keeps appointments secure, connects each booking to the right patient profile, and lets the admin team manage requests professionally.",
    createAccount: "Create Account",
    secureBooking: "Secure booking flow",
    chooseDoctorAfterLogin: "Choose doctor and time after login",
    jwtProtected: "JWT protected patient appointment",
    adminConfirm: "Admin can confirm or cancel request",
    bookVisit: "Book your visit with a specialist.",
    loggedInAs: "Logged in as",
    requestProtected: "Your request is protected with JWT and stored in MongoDB.",
    patientName: "Patient name",
    email: "Email",
    phone: "Phone",
    selectDepartment: "Select department",
    anyDoctor: "Any available doctor",
    symptoms: "Symptoms or notes",
    confirmAppointment: "Confirm Appointment",
    appointmentSuccess: "Appointment booked successfully. Admin can now manage it from dashboard.",
    appointmentError: "Unable to book appointment.",
    contactTitle: "Need support? Send an inquiry to our care desk.",
    contactText: "Admin users can view, review, resolve, and delete inquiries from the dashboard.",
    fullName: "Full name",
    emailAddress: "Email address",
    phoneNumber: "Phone number",
    subject: "Subject",
    message: "Message",
    sendInquiry: "Send Inquiry",
    inquirySent: "Inquiry sent. The hospital team will respond shortly.",
    inquiryError: "Unable to send inquiry.",
    patientRegister: "Patient register",
    welcomeBack: "Welcome back.",
    password: "Password",
    login: "Login",
    loginFailed: "Login failed.",
    newPatient: "New patient?",
    patientRegisterTitle: "Create patient account.",
    register: "Register",
    registrationFailed: "Registration failed.",
    alreadyRegistered: "Already registered?",
    explore: "Explore",
    footerText: "Premium multispecialty healthcare with modern technology and compassionate clinical teams.",
    adminLogin: "Admin Login"
    ,
    adminLoginFailed: "Admin login failed.",
    adminPanel: "Hospital operations panel.",
    adminEmail: "Admin email",
    openDashboard: "Open Dashboard",
    adminDashboard: "Admin dashboard",
    manageAdmin: "Manage doctors, appointments, and patient inquiries.",
    appointments: "Appointments",
    inquiries: "Inquiries",
    contacts: "Contacts",
    footerTagline: "Advanced bone, joint and multispeciality care",
    name: "Name",
    department: "Department",
    specialization: "Specialization",
    qualification: "Qualification",
    experience: "Experience",
    fee: "Fee",
    availableDaysPlaceholder: "Available days: Monday, Wednesday",
    addDoctor: "Add Doctor",
    saveDoctor: "Save Doctor",
    manageDoctors: "Manage Doctors",
    manageAppointments: "Manage Appointments",
    manageContactInquiries: "Manage Contact Inquiries",
    deleteDoctor: "Delete doctor",
    deleteInquiry: "Delete inquiry",
    loadAdminError: "Unable to load admin data.",
    doctorAdded: "Doctor added successfully.",
    saveDoctorError: "Unable to save doctor.",
    with: "with",
    on: "on",
    at: "at",
    pending: "pending",
    confirmed: "confirmed",
    completed: "completed",
    cancelled: "cancelled",
    newStatus: "new",
    reviewed: "reviewed",
    resolved: "resolved",
    toggleMenu: "Toggle menu"
  },
  HI: {
    home: "होम",
    about: "हमारे बारे में",
    departments: "विभाग",
    doctors: "डॉक्टर्स",
    contact: "संपर्क",
    admin: "एडमिन",
    hindi: "हिंदी",
    english: "English",
    patientLogin: "रोगी लॉगिन",
    logout: "लॉगआउट",
    bookAppointment: "अपॉइंटमेंट बुक करें",
    viewDepartments: "विभाग देखें",
    premiumHospital: "प्रीमियम आधुनिक अस्पताल",
    heroTitle: "शांत, सटीक और व्यवस्थित स्वास्थ्य सेवा।",
    heroText: "{hospital} विशेषज्ञ डॉक्टरों, डिजिटल अपॉइंटमेंट, 24/7 आपातकालीन देखभाल और प्रीमियम रोगी अनुभव को साथ लाता है।",
    doctorsStat: "डॉक्टर्स",
    yearsStat: "वर्ष",
    yearsShort: "वर्ष",
    satisfactionStat: "संतुष्टि",
    liveEmergency: "लाइव इमरजेंसी कमांड",
    certifiedCare: "प्रमाणित विशेषज्ञ देखभाल",
    whyChoose: "हमें क्यों चुनें",
    professionalCare: "प्रीमियम डिजिटल सुविधा के साथ प्रोफेशनल केयर।",
    specialistLed: "विशेषज्ञों द्वारा उपचार",
    specialistLedText: "महत्वपूर्ण विभागों में अनुभवी डॉक्टरों से परामर्श लें।",
    fastAppointments: "तेज अपॉइंटमेंट",
    fastAppointmentsText: "रोगी सुरक्षित तरीके से रजिस्टर, लॉगिन और अपॉइंटमेंट बुक कर सकते हैं।",
    premiumExperience: "प्रीमियम अनुभव",
    premiumExperienceText: "साफ इंटरफेस, सहज होवर प्रभाव और हर स्क्रीन पर सही दिखने वाला हेल्थकेयर लेआउट।",
    aboutHospital: "अस्पताल के बारे में",
    aboutTitle: "{hospital} आधुनिक और भरोसेमंद स्वास्थ्य सेवा के लिए बना है।",
    aboutText1: "हम वरिष्ठ सलाहकारों, आधुनिक जांच सुविधाओं, आपातकालीन सहायता और रोगी-केंद्रित डिजिटल सेवाओं के साथ मल्टीस्पेशलिटी देखभाल देते हैं।",
    aboutText2: "इस प्लेटफॉर्म में रोगी लॉगिन, अपॉइंटमेंट बुकिंग, एडमिन डैशबोर्ड, डॉक्टर प्रबंधन, पूछताछ ट्रैकिंग और भूमिका-आधारित पहुंच शामिल है।",
    emergencyCare: "इमरजेंसी केयर",
    eightMin: "8 मिनट",
    avgResponse: "औसत प्रतिक्रिया",
    qualityOps: "क्वालिटी आधारित संचालन",
    departmentsTitle: "हर उपचार चरण के लिए विशेषज्ञ विभाग।",
    doctorsTitle: "प्रीमियम केयर विभागों के अनुभवी कंसल्टेंट से मिलें।",
    appointmentBooking: "अपॉइंटमेंट बुकिंग",
    loginFirstTitle: "अपॉइंटमेंट बुक करने से पहले लॉगिन करें।",
    loginFirstText: "रोगी लॉगिन अपॉइंटमेंट को सुरक्षित रखता है, बुकिंग को सही प्रोफाइल से जोड़ता है और एडमिन टीम को अनुरोध प्रबंधित करने में मदद करता है।",
    createAccount: "अकाउंट बनाएं",
    secureBooking: "सुरक्षित बुकिंग फ्लो",
    chooseDoctorAfterLogin: "लॉगिन के बाद डॉक्टर और समय चुनें",
    jwtProtected: "सुरक्षित रोगी अपॉइंटमेंट",
    adminConfirm: "एडमिन अनुरोध की पुष्टि या उसे रद्द कर सकता है",
    bookVisit: "विशेषज्ञ से मुलाकात बुक करें।",
    loggedInAs: "लॉगिन:",
    requestProtected: "आपका अनुरोध सुरक्षित है और डेटाबेस में रखा गया है।",
    patientName: "रोगी का नाम",
    email: "ईमेल",
    phone: "फोन",
    selectDepartment: "विभाग चुनें",
    anyDoctor: "कोई भी उपलब्ध डॉक्टर",
    symptoms: "लक्षण या नोट्स",
    confirmAppointment: "अपॉइंटमेंट की पुष्टि करें",
    appointmentSuccess: "अपॉइंटमेंट बुक हो गया। एडमिन इसे डैशबोर्ड से प्रबंधित कर सकता है।",
    appointmentError: "अपॉइंटमेंट बुक नहीं हो पाया।",
    contactTitle: "सहायता चाहिए? हमारे सहायता कक्ष को पूछताछ भेजें।",
    contactText: "एडमिन डैशबोर्ड से पूछताछ देखी, समीक्षा की, हल की और हटाई जा सकती है।",
    fullName: "पूरा नाम",
    emailAddress: "ईमेल एड्रेस",
    phoneNumber: "फोन नंबर",
    subject: "विषय",
    message: "संदेश",
    sendInquiry: "पूछताछ भेजें",
    inquirySent: "पूछताछ भेज दी गई है। हमारी टीम जल्द संपर्क करेगी।",
    inquiryError: "पूछताछ भेजी नहीं जा सकी।",
    patientRegister: "रोगी रजिस्टर",
    welcomeBack: "वापसी पर स्वागत है।",
    password: "पासवर्ड",
    login: "लॉगिन",
    loginFailed: "लॉगिन असफल।",
    newPatient: "नए रोगी?",
    patientRegisterTitle: "रोगी अकाउंट बनाएं।",
    register: "रजिस्टर",
    registrationFailed: "रजिस्ट्रेशन असफल।",
    alreadyRegistered: "पहले से रजिस्टर हैं?",
    explore: "एक्सप्लोर",
    footerText: "आधुनिक तकनीक और संवेदनशील चिकित्सा टीमों के साथ प्रीमियम मल्टीस्पेशलिटी स्वास्थ्य सेवा।",
    adminLogin: "एडमिन लॉगिन"
    ,
    adminLoginFailed: "एडमिन लॉगिन असफल।",
    adminPanel: "अस्पताल संचालन पैनल।",
    adminEmail: "एडमिन ईमेल",
    openDashboard: "डैशबोर्ड खोलें",
    adminDashboard: "एडमिन डैशबोर्ड",
    manageAdmin: "डॉक्टर, अपॉइंटमेंट और रोगी पूछताछ प्रबंधित करें।",
    appointments: "अपॉइंटमेंट",
    inquiries: "पूछताछ",
    contacts: "संपर्क",
    footerTagline: "हड्डी, जोड़ और मल्टीस्पेशलिटी की उन्नत देखभाल",
    name: "नाम",
    department: "विभाग",
    specialization: "विशेषज्ञता",
    qualification: "योग्यता",
    experience: "अनुभव",
    fee: "फीस",
    availableDaysPlaceholder: "उपलब्ध दिन: सोमवार, बुधवार",
    addDoctor: "डॉक्टर जोड़ें",
    saveDoctor: "डॉक्टर सहेजें",
    manageDoctors: "डॉक्टर प्रबंधित करें",
    manageAppointments: "अपॉइंटमेंट प्रबंधित करें",
    manageContactInquiries: "संपर्क पूछताछ प्रबंधित करें",
    deleteDoctor: "डॉक्टर हटाएं",
    deleteInquiry: "पूछताछ हटाएं",
    loadAdminError: "एडमिन डेटा लोड नहीं हो पाया।",
    doctorAdded: "डॉक्टर सफलतापूर्वक जोड़ दिया गया।",
    saveDoctorError: "डॉक्टर सहेजा नहीं जा सका।",
    with: "के साथ",
    on: "को",
    at: "पर",
    pending: "पेंडिंग",
    confirmed: "पुष्ट",
    completed: "पूरा",
    cancelled: "रद्द",
    newStatus: "नया",
    reviewed: "रिव्यू किया गया",
    resolved: "हल किया गया",
    toggleMenu: "मेनू खोलें या बंद करें"
  }
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem("siteLanguage") || "EN");

  function toggleLanguage() {
    setLanguage((current) => {
      const next = current === "EN" ? "HI" : "EN";
      localStorage.setItem("siteLanguage", next);
      return next;
    });
  }

  const value = useMemo(() => ({
    language,
    toggleLanguage,
    t: (key) => translations[language][key] || translations.EN[key] || key
  }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  return useContext(LanguageContext);
}
